### PR TITLE
added some important keys

### PR DESCRIPTION
**Pull request by toxydose**
was not presented some important keys.
added keys:
TAB
ESCAPE
BACKSPACE
DELETE
PRINT SCREEN

### CODE REVIEW

**Comment by ArminJo** [comment]
This pull request is included in the new [version 1.6.8](https://github.com/ArminJo/DigistumpArduino) of Digistump avr core.

**Comment by ArminJo** [comment]
This pull request is included in the new [version 1.6.8](https://github.com/ArminJo/DigistumpArduino) of Digistump avr core.

**Comment by ArminJo** [comment]
So please close the pull request, since this repo is abandoned.

**Comment by toxydose** [comment]
Sure, thanks

**Pull request closed without merging**
